// Generated by scripts/home-template-hashes.ts; do not edit by hand.
/** sha256 of every earlier shipped version of each upgradable home template file (not the current one). */
export const SHIPPED_TEMPLATE_HASHES: Record<string, readonly string[]> = {
  "AGENTS.md": [
    "200998d25e337b4b1210c77ae72ebee4e56a5eadd436c363e19fe23de26a90e5",
    "2caa04afc6e847e6b8953ef095dc275238d543452bb7d421214c40818472f243",
    "2d3a616b72235652ee95a6af316d5001fc39c29008fb04613baad110f8901807",
    "439b795666f2bc7edff3fdb3f8b97a853eb8118bf349ce68e1171edc1f1021a0",
    "670493afb42c0b3c67659fdce567d9ccc84018f50d31e5ee045b1ead2e5b8f2a",
    "6b8047babb11f4e20bd1c71e98045d23d7c968d2530b6ecb1278053fd8fd004b",
    "6c093d36d4462368fe88c3cc5bf199c80270eb665a7d626d74e8501ef6931e77",
    "8825a571737d90148c5685c4e2bb040cea84ab8c573457b47263b607c0c3d293",
    "976c312ee5970268f2620d07b3ecacc6f9ceb0e42a70f7398905f26b449ee361",
    "9b57cfc8fdd0e6e9633343309944e4c22fb62559ab2d62044233bbd34a183ce1",
    "a0d9c5dc1cdddb57e675b9e6ed949a1275d8ce86b48dc9a569219212b7c3c7b6",
    "a3434479f24ad0587489a894aa655be0e0c0eb7f56c80341f4c332c099e23a0c",
    "a8e17a585e9695b9bb1801efbafd759ecfa87aabc3891a7965e88daab9be3620",
    "b4456357e6b4264403c4be767841669672d3776df11dd5cfb4c2392ea49215ed",
    "c1b17650b71bb83b6ad760a44412470e78c563248ceacea67beaf91d1123d3d8",
    "d072f081416c002dd7ecf69618532bc8dabe30e3b7c7ed43d4abc2a33ba32e30",
    "e667d90ff30d42549bd6daa4d199d7aec1d1bb8e34e40924bb075f7bdb54c009",
  ],
  "SOUL.md": [],
  "schedule.md": [],
  "gitignore": [
    "070b87fad632d447c5078ac73256bc21fdab6719aea685798fcebfb2445eb571",
    "5953885b8859fece1d9b38547d1d000cbeab68b08fbfc3253e15012d074304ee",
    "7eac7f2093070ddee357432b7d35666a68b021c84ae06a1b028cbcd528e057c0",
  ],
  "agents-skills-README.md": [],
  "agents-skills-session-history-SKILL.md": [
    "22b564392c2806df78ee94354d5eb275389ecda442eafbc16316db64383b773c",
    "82acfdd5715d77766e9a130da9ba1c41d7c42624487e0e3e6f92f4711403fbf2",
    "b7000898cf1bed4d187adbd10193a9765a26b7be47b042c67a10e259f059546d",
  ],
  "agents-skills-documents-SKILL.md": [
    "7eca8d497f561e3191aaedfafdad316334e9116c18056fb4a63eaaec7b6560a7",
    "e791de5521f3e7a6239dd677d34111c2a0b4d73c3fc1372a8b1ea611c786d4b2",
  ],
  "agents-agents-explore.md": [],
  "agents-agents-researcher.md": [
    "a2ddf63c1e756f7c2e2dcedc95cc2a3957c19af9f64c8fdcd56782afe1a9dbb6",
  ],
  "agents-agents-reviewer.md": [
    "ff2ad6780302b8e5db9b36e77ab9d726aa7f410a31bf35fe0ca48cb0223fac09",
  ],
  "agents-agents-coder.md": [],
};
