import { SpanStatusCode } from "@opentelemetry/api";
import type { Client } from "discord.js";
import { join } from "node:path";
import { config } from "../../config.ts";
import { getDb } from "../../db/index.ts";
import { getLogger } from "../../logger.ts";
import { tracer } from "../../telemetry.ts";
import { getUnprocessedMessages, getWikiSyncWatermark, setWikiSyncWatermark } from "../../db/wikiSync.ts";
import { COMMITTER_NAME, openWikiRepo } from "./git.ts";
import { writeMessageInbox } from "./inbox.ts";
import { postSyncStatus } from "./notify.ts";
import { runWikiSyncSession } from "./piSession.ts";
import { buildSweepTriggerPrompt } from "./prompt.ts";

const logger = getLogger("wiki-sync:sweep");

/** Guards against the cron tick and an on-demand /wiki-sync command racing on the same working tree. */
const inFlight = new Set<string>();

const RETENTION_MS = 30 * 24 * 60 * 60 * 1000;

// Primary sweep-size boundary: a few calendar days of backlog, not an arbitrary message count.
// A count-only cap either truncates a normal day's chatter for no reason, or (backlog catch-up,
// a raid, an unusually busy day) lets a single sweep's input balloon to whatever volume happened
// to land in an unbounded window -- the exact axis that risked a stuck/overlong sweep before.
// 3 days gives headroom over the daily cron's actual cadence so this boundary basically never
// triggers in steady state; maxMessagesPerSweep is the real backstop for an abnormally busy span.
const MAX_SWEEP_SPAN_MS = 3 * 24 * 60 * 60 * 1000;

export interface SweepResult {
  ran: boolean;
  reason?: string;
  commitSha?: string | null;
}

/** True if a sweep for this guild is already running — lets a caller (e.g. the /wiki-sync command) decide upfront without waiting on runWikiSyncSweep itself. */
export function isSweepInFlight(guildId: string): boolean {
  return inFlight.has(guildId);
}

/**
 * `runId` correlates this call across the immediate command reply, logs, and the eventual
 * status-channel post — generated by the caller (e.g. a short id shown to the user right away)
 * when the caller isn't going to wait for this promise to resolve. Defaults to a fresh one for
 * callers that don't care (the scheduler).
 */
export async function runWikiSyncSweep(guildId: string, client: Client, runId: string = crypto.randomUUID().slice(0, 8)): Promise<SweepResult> {
  if (inFlight.has(guildId)) {
    return { ran: false, reason: "a sweep is already running for this guild" };
  }
  inFlight.add(guildId);

  // Span name/attributes follow the OTel GenAI semantic conventions' "invoke_agent" span
  // (gen-ai-agent-spans.md): one whole agent run, of which each model turn below is a nested
  // "chat" span. wiki_sync.* attributes stay custom -- no standard slot for guild/run identity.
  return tracer.startActiveSpan(
    `invoke_agent ${COMMITTER_NAME}`,
    {
      attributes: {
        "gen_ai.operation.name": "invoke_agent",
        "gen_ai.agent.name": COMMITTER_NAME,
        "wiki_sync.guild_id": guildId,
        "wiki_sync.run_id": runId,
      },
    },
    async (span) => {
    const db = getDb();
    const log = logger.child({ guildId, runId });
    try {
      // Floor against the message-retention window so a stale/missing watermark (first run,
      // long-dead bot) can't try to scan further back than the DB actually has.
      const floor = Date.now() - RETENTION_MS;
      const watermark = Math.max(getWikiSyncWatermark(db, guildId), floor);
      // Never past "now" -- a fresh/caught-up watermark shouldn't produce a window into the
      // future. During backlog catch-up this instead lands one day past the watermark, well
      // short of "now", so subsequent sweeps keep walking forward day by day.
      const until = Math.min(watermark + MAX_SWEEP_SPAN_MS, Date.now());

      const messages = getUnprocessedMessages(db, guildId, watermark, until, config.wikiSync.maxMessagesPerSweep);
      span.setAttribute("wiki_sync.message_count", messages.length);
      if (messages.length === 0) {
        // Advance to the window's end, not Date.now() -- jumping straight to "now" would skip
        // over any days between `until` and now that do have messages still waiting.
        setWikiSyncWatermark(db, guildId, until);
        span.setAttribute("wiki_sync.reason", "no new messages");
        return { ran: true, reason: "no new messages" };
      }

      const repo = await openWikiRepo(guildId);
      // Sibling of the repo checkout, outside its git working tree entirely — see inbox.ts.
      const inboxDir = join(config.wikiSync.inboxDir, guildId);

      // The status channel (and any thread on a message wiki-sync posted there, e.g. the
      // per-sweep "discuss this sync" thread from notify.ts) isn't community content to build
      // wiki pages from -- it's where people talk about wiki-sync's own output. Routed to
      // buildSweepTriggerPrompt's separate feedback section instead of the regular content list.
      const statusChannelId = config.guildConfig[guildId]?.wiki?.statusChannelId;
      const contentMessages = statusChannelId
        ? messages.filter((m) => m.channelId !== statusChannelId && m.parentChannelId !== statusChannelId)
        : messages;
      const feedbackMessages = statusChannelId
        ? messages.filter((m) => m.channelId === statusChannelId || m.parentChannelId === statusChannelId)
        : [];

      const { files } = await writeMessageInbox(inboxDir, client, contentMessages);
      const feedbackFiles =
        feedbackMessages.length > 0 ? (await writeMessageInbox(inboxDir, client, feedbackMessages, { clear: false })).files : [];
      const prompt = buildSweepTriggerPrompt(files, feedbackFiles);
      const result = await runWikiSyncSession({ repo, prompt, guildId, runId });
      span.setAttribute("wiki_sync.commit_sha", result.commitSha ?? "");

      // Advance past exactly the messages this sweep saw. A crash before this point leaves the
      // watermark untouched, so the same batch is retried rather than silently skipped.
      const latest = messages[messages.length - 1];
      if (latest) setWikiSyncWatermark(db, guildId, latest.createdAt);

      if (result.commitSha) {
        await postSyncStatus({ client, guildId, repo, commitSha: result.commitSha });
      }

      log.info({ messageCount: messages.length, commitSha: result.commitSha }, "sweep complete");
      return { ran: true, commitSha: result.commitSha };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      span.recordException(err instanceof Error ? err : errMsg);
      span.setStatus({ code: SpanStatusCode.ERROR, message: errMsg });
      throw err;
    } finally {
      span.end();
      inFlight.delete(guildId);
    }
  });
}
