#!/usr/bin/env bun
// Regenerates src/workspace/homeTemplateHashes.ts: the sha256 of every version of each upgradable home
// template file ever committed on any local branch, minus the current one. Run after changing a template
// (or merging a branch that did): `bun scripts/home-template-hashes.ts`.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { UPGRADABLE_TEMPLATES } from "../src/workspace/homeUpgrade.ts";

const root = join(import.meta.dir, "..");
const templateDir = "src/workspace/home-template";

function git(args: string[]): string {
  const res = Bun.spawnSync(["git", ...args], { cwd: root });
  if (res.exitCode !== 0) throw new Error(`git ${args.join(" ")} failed: ${res.stderr.toString()}`);
  return res.stdout.toString();
}

const sha = (text: string) => createHash("sha256").update(text).digest("hex");

const out: Record<string, string[]> = {};
for (const file of Object.values(UPGRADABLE_TEMPLATES)) {
  const path = `${templateDir}/${file}`;
  const current = sha(readFileSync(join(root, path), "utf8"));
  const revs = git(["log", "--all", "--full-history", "--format=%H", "--", path]).split("\n").filter(Boolean);
  const hashes = new Set<string>();
  for (const rev of revs) {
    let text: string;
    try {
      text = git(["show", `${rev}:${path}`]);
    } catch {
      continue; // the commit deleted it
    }
    const h = sha(text);
    if (h !== current) hashes.add(h);
  }
  out[file] = [...hashes].sort();
}

const body = Object.entries(out)
  .map(([file, hashes]) => `  ${JSON.stringify(file)}: [${hashes.length ? `\n${hashes.map((h) => `    "${h}",`).join("\n")}\n  ` : ""}],`)
  .join("\n");
writeFileSync(
  join(root, "src/workspace/homeTemplateHashes.ts"),
  `// Generated by scripts/home-template-hashes.ts; do not edit by hand.\n/** sha256 of every earlier shipped version of each upgradable home template file (not the current one). */\nexport const SHIPPED_TEMPLATE_HASHES: Record<string, readonly string[]> = {\n${body}\n};\n`,
);
console.log(Object.entries(out).map(([f, h]) => `${f}: ${h.length}`).join("\n"));
